export const Actions = {
  INCREMENT: 'Increment',
  SET_ACTIVE_TOOL: 'SetActiveTool',
  SET_ACTIVE_COLOR_NAME: 'SetActiveColorName',
  SET_ACTIVE_COLOR_HEX: 'SetActiveColorHex',
  SET_ACTIVE_COLOR_INT: 'SetActiveColorInt',
  SET_LOADING_STATUS: 'SetLoadingStatus',
  ADD_PIXEL_TO_ARRAY: 'AddPixelToArray',
  REMOVE_PIXEL_FROM_ARRAY: 'RemovePixelFromArray',
  CLEAR_PIXEL_ARRAY: 'ClearPixelArray',
  SET_API: 'SetApi',
  SET_LAST_REFRESH: 'SetLastRefresh',
  SET_SENDING_TRANSACTION: 'SetSendingTransaction',
  SET_SCATTER: 'SetScatter',
  SET_IDENTITY: 'SetIdentity',
  SET_CANVASSE: 'SetCanvasse',
  LOAD_CONTRACT_CONFIG: 'LoadContractConfig',
  LOAD_CONTRACT_ACCOUNT: 'LoadContractAccount',
  SET_MOUSE_COORDS: 'SetMouseCoords',
  SET_ZOOM_LEVEL: 'SetZoomLevel',
  LOAD_PAINT_HISTORY: 'LoadPaintHistory',
  PUSH_CHAT_HISTORY: 'PushChatHistory',
  LOAD_LEADERBOARD: 'LoadLeaderboard',
  SET_COOLDOWN_EXPIRES: 'SetCooldownExpires',
  SET_PIXELS_REMAINING: 'SetPixelsRemaining'
}
